spring:
  application:
    name: dataflow
  
  profiles:
    active: dev

server:
  port: 8080
  servlet:
    context-path: /dataflow

logging:
  level:
    root: INFO
    com.tencent.dataflow: DEBUG

# MyBatis-Plus 全局配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      # 逻辑删除配置
      logic-delete-field: deleted     # 全局逻辑删除字段名
      logic-delete-value: true        # 逻辑已删除值(布尔)
      logic-not-delete-value: false   # 逻辑未删除值(布尔)
  type-handlers-package: com.baomidou.mybatisplus.extension.handlers
